export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',

	SET_COUNTER: 'SET_COUNTER',
	CONNECT_WALLET: 'CONNECT_WALLET',

	TOGGLE_CREATE_EVENT_EFFECT: 'TOGGLE_CREATE_EVENT_EFFECT'
};
